name: flutter_lock_screen
description: A new Flutter project.
version: 0.0.1
author: Yasin ilhan<yasinilhan61@gmail.com>
homepage: https://github.com/kalismeras61/flutter_lock_screen

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  fonts:
    - family: Open Sans
      fonts:
        - asset: fonts/OpenSans-Regular.ttf
        - asset: fonts/OpenSans-Light.ttf
          weight: 300
        - asset: fonts/OpenSans-Bold.ttf
          weight: 700

  #
  # For details regarding fonts in packages, see
  # https://flutter.io/custom-fonts/#from-packages
